cache:
  untracked: true
  key: '$CI_BUILD_REF_NAME'
  paths:
    - node_modules/

stages:
  - install_deps
  - test

# 安装依赖
npm_install:
  stage: install_deps
  script:
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - npm update fe-check -g # 每次更新此模块时，同时更新 CI 机器该模块版本
# 运行测试用例
npm_test:
  stage: test
  script:
    - npm test
